version: "2"
services:

  db:
    image: mysql:latest
    ports:
        - "3306:3306"
    environment:
         - MYSQL_DATABASE=yii2
         - MYSQL_ROOT_PASSWORD=root
         - character-set-server=utf8


  apache:
    build: ../Web/.
    ports:
        - "8080:80"
    links:
        - db
    volumes:
        - /c/Users/beats/Documents/php_development/:/var/www/
